#ifndef PLUGINCONTROL_GLOBAL_H
#define PLUGINCONTROL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PLUGINCONTROL_LIB
# define PLUGINCONTROL_EXPORT Q_DECL_EXPORT
#else
# define PLUGINCONTROL_EXPORT Q_DECL_IMPORT
#endif

#endif // PLUGINCONTROL_GLOBAL_H
