#ifndef MAINFRAME_GLOBAL_H
#define MAINFRAME_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef MAINFRAME_LIB
# define MAINFRAME_EXPORT Q_DECL_EXPORT
#else
# define MAINFRAME_EXPORT Q_DECL_IMPORT
#endif

#endif // MAINFRAME_GLOBAL_H