#ifndef SIGNAL__
#define SIGNAL__

#define    SIG_WINDOWCLOSE			 0x010
#define    SIG_CLOSE                 0X020
#define	   SIG_WINDOWMAX			 0x030
#define	   SIG_WINDOWMIN			 0x040
#define	   SIG_WINDOWEXIT			 0x055
#define	   SIG_FREEPLUG				 0x065
#define	   SIG_LOADPLUG				 0x075
#define	   SIG_WRITELOG				 0x080
#define	   SIG_PLUGINNAMECHANGED     0x090
#define    SIG_INITIALIZENETWORK     0x0100
#define    SIG_SHOW_ABSTRACTWIDGET   0x0110
#define	   SIG_SWITCHPLUGIN			 0x0120
#define	   SIG_INVALID				(SIG_SWITCHPLUGIN) + 1

enum class Signal_ {
	WINDOWCLOSE =			SIG_WINDOWCLOSE,
	CLOSE =                 SIG_CLOSE,
	WINDOWMAX =				SIG_WINDOWMAX,
	WINDOWMIN =				SIG_WINDOWMIN,
	WINDOWEXIT =			SIG_WINDOWEXIT,
	FREEPLUG =				SIG_FREEPLUG,
	LOADPLUG =				SIG_LOADPLUG,
	WRITELOG =				SIG_WRITELOG,
	PLUGINNAMECHANGED =		SIG_PLUGINNAMECHANGED,
	INITIALIZENETWORK =		SIG_INITIALIZENETWORK,
	SHOW_ABSTRACTWIDGET =   SIG_SHOW_ABSTRACTWIDGET,
	SWITCHPLUGIN =			SIG_SWITCHPLUGIN,
	INVALID =				SIG_INVALID
};
 
enum class SystemUser{
	MAINFRAME, 
	MESSAGE,
	MAINWIDGET,
};


#endif //SIGNAL__